stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - params.yaml
      - src/data/data_ingestion.py
    outs:
      - data/raw
    
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    params:
      - data_ingestion.test_size
    outs:
      - data/interim

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/interim/train_processed.csv
    params:
      - model_building.max_features
      - model_building.ngram_range
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl